repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--check", "."]
        pass_filenames: false
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--extend-ignore=E501]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: git-add-all
        name: Auto-stage modified files
        entry: git add -u
        language: system
        pass_filenames: false
