preflight: false
project:
  out_dir: raporlar
  run_mode: range
  start_date: "2025-03-07"
  end_date: "2025-03-11"
  holding_period: 1
  transaction_cost: 0.0
  stop_on_filter_error: false
  raise_on_error: false

data:
  excel_dir: data
  filters_csv: filters.csv
  enable_cache: false

calendar:
  tplus1_mode: price

  indicators:
    engine: none
    params: {}

  benchmark:
    source: none
    excel_path: ""
    excel_sheet: BIST
    csv_path: ""
    column_date: date
    column_close: close

report:
  percent_format: "0.00%"
  daily_sheet_prefix: "SCAN_"
  summary_sheet_name: "SUMMARY"
