version: 1
formatters:
  standard:
    format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s'
filters:
  error_counter:
    "()": finansal_analiz_sistemi.logging_utils.ErrorCountingFilter
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    filters: [error_counter]
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/fas_%Y-%m-%d.log
    level: DEBUG
    formatter: standard
    when: midnight
    backupCount: 14
    filters: [error_counter]
loggers:
  finansal_analiz_sistemi:
    level: DEBUG
    handlers: [console, file]
    propagate: False
root:
  level: INFO
  handlers: [console, file]
