[tool.black]
line-length = 88

[tool.poetry]
name = "finansal-analiz-sistemi"
version = "0.1.0"
description = "Backtest otomasyon projesi"
authors = []

[tool.poetry.dependencies]
python = "^3.11"
pandas-ta = "0.3.14b0"
cachetools = "6.1.0"
xlsxwriter = "^3.1"
hypothesis = "^6.102"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]

[tool.isort]
profile = "black"
line_length = 88
