[tool.black]
line-length = 88

[tool.poetry]
name = "finansal-analiz-sistemi"
version = "0.1.0"
description = "Backtest otomasyon projesi"
authors = []

[tool.poetry.dependencies]
python = "^3.11"
pandas-ta-openbb = "0.4.22"
cachetools = "5.5.2"
numpy = "2.0.2"
pandas = "2.2.2"
xlsxwriter = "3.2.5"
hypothesis = ">=6.102"
openpyxl = "3.1.5"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
explicit_package_bases = true
ignore_errors = true

[tool.poetry.packages]
include = "finansal_analiz_sistemi"

