project:
  out_dir: "../raporlar"
  logs_dir: "../loglar"
  run_mode: "range"
  holding_period: 1
  transaction_cost: 0.0
  stop_on_filter_error: false

data:
  excel_dir: "../data"
  filters_csv: "../filters.csv"
  enable_cache: false
  cache_parquet_path: "../cache"

filters:
  module: io_filters
  include: ["*"]

calendar:
  tplus1_mode: "calendar"
  holiday_csv: ""

benchmark:
  source: "excel"
  excel_path: "../data/BIST.xlsx"
  excel_sheet: "BIST"
  csv_path: ""
  column_date: "date"
  column_close: "close"

report:
  with_bist_ratio_summary: true
  include_hit_ratio: true
  excel_engine: "xlsxwriter"

range:
  start_date: "2022-01-03"
  end_date: "2025-04-18"

single:
  date: "2025-03-07"
preflight: true
