
project:
  out_dir: "raporlar"
  run_mode: "range"
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  single_date: null
  holding_period: 1
  transaction_cost: 0.0
  stop_on_filter_error: false
  
data:
  excel_dir: "../data"
  enable_cache: false
  cache_parquet_path: "cache/prices.parquet"
  price_schema:
    date: ["Tarih","Date","tarih"]
    open: ["Açılış","Open"]
    high: ["Yüksek","High"]
    low:  ["Düşük","Low"]
    close: ["Kapanış","Close"]
    volume: ["Hacim","Volume","Adet"]

calendar:
  tplus1_mode: "price"   # price: sembol-bazlı bir sonraki bar; calendar: takvim bazlı T+1
  holidays_source: "none"   # none | csv
  holidays_csv_path: ""      # ör: examples/holidays_tr.csv

indicators:
  engine: "none"
  params:
    rsi: [14]
    ema: [10,20,50]
    macd: [12,26,9]

benchmark:
  source: "none"
  excel_path: ""
  excel_sheet: "BIST"
  csv_path: ""
  column_date: "date"
  column_close: "close"

report:
  percent_format: "0.00%"
  daily_sheet_prefix: "SCAN_"
  summary_sheet_name: "SUMMARY"
filters:
  module: "io_filters"
  include: ["*"]
