name: Benchmark

on:
  push:
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Run benchmark
        run: |
          python benchmarks/benchmark.py
      - name: Verify output
        run: |
          if [ ! -f benchmarks/benchmark_output.txt ]; then
            echo "benchmark output missing" >&2
            exit 1
          fi
      - name: Display result
        run: cat benchmarks/benchmark_output.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_output
          path: benchmarks/benchmark_output.txt
