name: tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: artifacts
      LOG_DIR: loglar
      EXCEL_DIR: Veri
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Kurulum
      - run: pip install -r requirements.txt || true
      - run: pip install -r requirements-dev.txt

      # Fixtures + golden verification + quality + preflight + test
      - run: make fixtures
      - run: make validate
      - run: make golden-verify
      - run: make quality
      - run: make preflight
      - run: make guardrails
      - run: make test
      - name: download-smoke
        run: |
          python -m backtest.cli fetch-range --symbols DEMO --start 2025-03-07 --end 2025-03-21 --provider stub
          python -m backtest.cli integrity-check --symbols DEMO --provider stub
      - name: Upload download artifacts
        uses: actions/upload-artifact@v4
        with:
          name: download-smoke
          path: |
            data/parquet
            artifacts/data/integrity_report.json
          if-no-files-found: ignore
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: loglar
