name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install project and dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas-ta==0.3.14b0
          pip install --timeout 60 -r requirements.txt
          pip install --timeout 60 matplotlib xlsxwriter streamlit
          pip install -e .

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt && pip install "pandas==${{ matrix.pandas-version }}"

      - name: Lint & Tests via pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: |
          pytest -q
          pytest -q tests/test_report_format.py
      - name: Run simple backtest
        run: |
          python - <<'PY'
          import pandas as pd, report_generator, os
          os.makedirs('cikti/raporlar', exist_ok=True)
          df = pd.DataFrame({'filtre_kodu':['F1'], 'bulunan_hisse_sayisi':[1], 'ortalama_getiri':[1.0], 'notlar':[''], 'tarama_tarihi':['01.01.2025'], 'satis_tarihi':['02.01.2025']})
          report_generator.kaydet_uc_sekmeli_excel('cikti/raporlar/rapor_ci.xlsx', df, df, df)
          PY
      - name: Generate health report
        run: |
          python - <<'PY'
          import log_to_health, os, glob
          os.makedirs('cikti/raporlar', exist_ok=True)
          log_files = glob.glob('*.log') or ['ci.log']
          if log_files == ['ci.log']:
              open('ci.log','w').write('ci log')
          log_to_health.generate(log_files[-1], ['cikti/raporlar/rapor_ci.xlsx'])
          PY

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*.xlsx'

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t finansal_analiz:latest .
