name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Bütün bağımlılıkları (pytest dâhil) kur
      - run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          python -m pip install --upgrade pip
          pip install --timeout 60 --retries 3 -r requirements.txt
        env:
          GIT_TERMINAL_PROMPT: 0

      - run: pytest -q

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t finansal_analiz:latest .
