name: tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: artifacts
      LOG_DIR: loglar
      EXCEL_DIR: Veri
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Kurulum
      - run: pip install -r requirements.txt || true
      - run: pip install -r requirements-dev.txt

      # Fixtures + golden verification + quality + preflight + test
      - run: make fixtures
      - run: make validate
      - run: make preflight
      - run: make golden-verify
      - run: make quality
      - run: make guardrails
      - run: make risk-smoke
      - run: make test

      - run: make report
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: |
            artifacts/report
            artifacts/profiles/pyinstrument_scan.html
      - name: Upload risk reports
        uses: actions/upload-artifact@v4
        with:
          name: risk-reports
          path: artifacts/risk
          if-no-files-found: ignore
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: loglar
