name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11']
        numpy: ['2.0.2']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install "numpy==${{ matrix.numpy }}"
      - run: pip install pandas-ta-openbb
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: pytest -q
