name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -q pip-tools
          pip install -q -r requirements.txt
          pip install -q pre-commit mypy pytest-cov
      - uses: pre-commit/action@v3.0.1
      - name: Type-check (mypy – toleranslı)
        run: mypy src tests || true
      - name: Run unit tests + coverage
        run: pytest -q --cov=src --cov-report=xml
      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
