name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
    - name: Install deps
      run: |
        pip install -q pip-tools
        pip install -q -r requirements.txt
      - uses: pre-commit/action@v3.0.1
      - name: Run tests
        run: pytest -q
