name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -q pip-tools
          pip install -q -r requirements.txt
          pip install -q flake8==7.0.0 isort==5.13.2 black==24.4.2 mypy pytest-cov
      - name: Lint (flake8 / isort / black)
        run: |
          flake8 src tests || exit 1
          isort --check src tests || exit 1
          black --check src tests || exit 1
      - name: Type-check (mypy – toleranslı)
        run: mypy src tests || true
      - name: Run unit tests + coverage
        run: pytest -q --cov=src --cov-report=xml
      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
