name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements-py312.lock.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - run: pip install -U pip
      - if: matrix.python-version == '3.12'
        run: pip install -r requirements-py312.lock.txt
      - run: pip install -e ".[dev]"
      - run: bash tools/ci_checks.sh

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python tools/release/build_release_notes.py --template RELEASE_NOTES_TEMPLATE.md --out dist/RELEASE_NOTES.md
      - uses: softprops/action-gh-release@v1
        with:
          body_path: dist/RELEASE_NOTES.md

  dry-run:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: bash tools/release/dry_run.sh
