name: tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Kurulum
      - run: pip install -r requirements.txt || true
      - run: pip install -r requirements-dev.txt

      # Fixtures + preflight + test
      - run: make fixtures
      - run: make preflight
      - run: make test

