name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_dev.txt -c constraints.txt --only-binary=:all: --no-binary=pandas-ta
      - name: Show versions
        run: pip freeze | grep -Ei 'pandas(-ta)?|numpy|pandera|PyYAML' || true
      - name: Run tests
        run: pytest -q
